// ============================================================
// expose-ops.js — Vue template bindings: management & workflow
// Manager, alerts, time report, WO requests, forecasting,
// create WO, inventory, completed orders, open orders
// ============================================================

import * as store from './libs/store.js';
import { OPEN_ORDER_STATUSES, CHUTE_PART_STATUSES,
         OPEN_ORDER_SORT_FIELDS, INVENTORY_TABS } from './libs/config.js';
import { enterInventoryView, enterWoRequestView, enterCreateWoView,
         enterOpenOrdersView, enterWoForecastingView,
         saveHeaderLinks, saveSplashLinks } from './pages/splash-view.js';
import { openManagerSection, loadKpiData, loadDelayedOrders,
         fetchPriorityOrders, updatePriority, updateAssignedOperator,
         handleAssignChange, submitCustomAssign, cancelCustomAssign,
         openNotesPanel, loadManagerAlerts,
         sendAiMessage, loadTimeReport,
         loadWoProblems, openWoProblemModal, closeWoProblemModal, confirmResolveWoProblem,
         openDelayedWoDetail, closeDelayedWoDetail } from './pages/manager-view.js';
import { openAlertResolve, submitAlertResolve } from './pages/manager-alerts.js';
import { loadOpenOrders, setSectionSort, openOrderSortIcon,
         setRowColor, effectiveRowColor, openOrderRowClass, openOrderColorDotClass,
         loadReminderEmail, saveReminderEmail,
         openOrderStatusClass, chuteStatusClass, openOrderHasLine3,
         cancelAddModal, parsePasteRows, saveOpenOrderRow,
         moveToSection, bulkChangeStatus,
         startCellEdit, saveCellEdit, cancelCellEdit, deleteOpenOrder,
         toggleOpenOrderExpand,
         openWoDetailPanel, closeWoDetailPanel,
         woDeptBadgeClass, woStatusBadgeClass } from './pages/open-orders-view.js';
import { onRowMouseDown, onRowMouseEnter, onRowDragStart, onRowDragEnd,
         onSectionDragOver, onSectionDragLeave, onSectionDrop, clearRowSelection,
         onScrollAreaDragOver, onGripDragStart, onGripDragEnd,
         onDropZoneDragOver, clearDropZone, reorderDrop } from './pages/open-orders-drag.js';
import { loadInventoryItems, switchInventoryTab,
         openPullForm, closePullForm, submitPull,
         openAddItemForm, closeAddItemForm, submitAddItem,
         openEditItemForm, closeEditItemForm, submitEditItem,
         confirmDeleteInventoryItem,
         openPullHistory, closePullHistory } from './pages/inventory-view.js';
import { loadWoRequests, submitWoRequestForm, deleteWoRequestItem,
         openWoRequestDetail, closeWoRequestDetail,
         saveWoRequestDetail, approveWoRequest,
         saveWoRequestInlineFields,
         checkWoRequestPartMatch, acceptSoHint, dismissSoHint,
         openSendToForecast, closeSendToForecast, submitSendToForecast,
         handleWoFileUploadForRequest } from './pages/wo-request-view.js';
import { loadForecastedItems,
         openDeleteConfirm, cancelDeleteForecast, confirmDeleteForecast,
         openMoveBackConfirm, cancelMoveBack, confirmMoveBack } from './pages/wo-forecasting-view.js';
import { loadCreateWoItems, confirmCreateWoItem, switchCreateWoTab, loadCreatedWoItems } from './pages/create-wo-view.js';
import { enterCompletedOrdersView, loadCompletedOrders, restoreCompletedOrder } from './pages/completed-orders-view.js';

export function buildOpsExpose() {
    return {
        // Manager AI chat
        aiChatOpen:     store.aiChatOpen,
        aiChatLoading:  store.aiChatLoading,
        aiChatInput:    store.aiChatInput,
        aiChatMessages: store.aiChatMessages,

        // Manager
        assignCustomInput:    store.assignCustomInput,
        managerSubView:       store.managerSubView,
        priorityDept:         store.priorityDept,
        priorityOrders:       store.priorityOrders,
        delayedOrders:        store.delayedOrders,
        delayedOrdersByDept:  store.delayedOrdersByDept,
        kpiStats:             store.kpiStats,
        kpiByOperator:        store.kpiByOperator,
        kpiCycleTime:         store.kpiCycleTime,
        kpiHoldReasons:       store.kpiHoldReasons,
        kpiOldestWos:         store.kpiOldestWos,
        managerAlerts:        store.managerAlerts,
        delayedWoCount:       store.delayedWoCount,
        managerAlertCount:    store.managerAlertCount,
        managerTotalBadge:    store.managerTotalBadge,

        // WO Problems
        woProblems:                 store.woProblems,
        woProblemCount:             store.woProblemCount,
        woProblemModalOpen:         store.woProblemModalOpen,
        woProblemTarget:            store.woProblemTarget,
        woProblemResolution:        store.woProblemResolution,
        woProblemResolutionError:   store.woProblemResolutionError,
        woProblemResolverName:      store.woProblemResolverName,
        woProblemResolverNameError: store.woProblemResolverNameError,

        // Manager functions
        openManagerSection, loadKpiData, loadDelayedOrders,
        fetchPriorityOrders, updatePriority, updateAssignedOperator,
        handleAssignChange, submitCustomAssign, cancelCustomAssign,
        openNotesPanel, loadManagerAlerts,
        sendAiMessage, loadTimeReport,
        delayedWoDetailOpen: store.delayedWoDetailOpen,
        delayedWoDetail:     store.delayedWoDetail,
        openDelayedWoDetail, closeDelayedWoDetail,
        loadWoProblems, openWoProblemModal, closeWoProblemModal, confirmResolveWoProblem,
        alertResolveOpen:      store.alertResolveOpen,
        alertResolveTarget:    store.alertResolveTarget,
        alertResolveType:      store.alertResolveType,
        alertResolveBy:        store.alertResolveBy,
        alertResolveByError:   store.alertResolveByError,
        alertResolveText:      store.alertResolveText,
        alertResolveTextError: store.alertResolveTextError,
        openAlertResolve, submitAlertResolve,

        // Time Report
        timeReportSessions:     store.timeReportSessions,
        timeReportFrom:         store.timeReportFrom,
        timeReportTo:           store.timeReportTo,
        timeReportTab:          store.timeReportTab,
        timeReportExpandedWo:   store.timeReportExpandedWo,
        timeReportExpandedPart: store.timeReportExpandedPart,
        timeReportByWo:         store.timeReportByWo,
        timeReportByPart:       store.timeReportByPart,

        // WO Requests
        woRequests:           store.woRequests,
        woRequestsLoading:    store.woRequestsLoading,
        woRequestForm:        store.woRequestForm,
        woRequestFormErrors:  store.woRequestFormErrors,
        woRequestSearch:      store.woRequestSearch,
        filteredWoRequests:   store.filteredWoRequests,
        selectedWoRequest:    store.selectedWoRequest,
        woRequestDetailForm:  store.woRequestDetailForm,
        woRequestInlineState: store.woRequestInlineState,
        woRequestSoHint:      store.woRequestSoHint,
        enterWoRequestView,
        submitWoRequestForm,
        deleteWoRequestItem,
        openWoRequestDetail,
        closeWoRequestDetail,
        saveWoRequestDetail,
        approveWoRequest,
        saveWoRequestInlineFields,
        checkWoRequestPartMatch, acceptSoHint, dismissSoHint,
        openSendToForecast, closeSendToForecast, submitSendToForecast,
        handleWoFileUploadForRequest,
        sendToForecastOpen:   store.sendToForecastOpen,
        sendToForecastTarget: store.sendToForecastTarget,
        sendToForecastForm:   store.sendToForecastForm,
        sendToForecastErrors: store.sendToForecastErrors,

        // WO Forecasting
        forecastingItems:  store.forecastingItems,
        forecastingLoading: store.forecastingLoading,
        forecastDeleteId:  store.forecastDeleteId,
        forecastMoveBackId: store.forecastMoveBackId,
        enterWoForecastingView, loadForecastedItems,
        openDeleteConfirm, cancelDeleteForecast, confirmDeleteForecast,
        openMoveBackConfirm, cancelMoveBack, confirmMoveBack,

        // Create WO
        createWoItems:       store.createWoItems,
        createWoLoading:     store.createWoLoading,
        createWoInlineState: store.createWoInlineState,
        createWoTab:         store.createWoTab,
        createdWoItems:      store.createdWoItems,
        enterCreateWoView, loadCreateWoItems, confirmCreateWoItem, switchCreateWoTab, loadCreatedWoItems,

        // Inventory
        inventoryTab:           store.inventoryTab,
        inventoryItems:         store.inventoryItems,
        inventoryLoading:       store.inventoryLoading,
        inventorySearch:        store.inventorySearch,
        filteredInventoryItems: store.filteredInventoryItems,
        pullFormOpen:           store.pullFormOpen,
        pullFormTarget:         store.pullFormTarget,
        pullForm:               store.pullForm,
        pullFormErrors:         store.pullFormErrors,
        addItemFormOpen:        store.addItemFormOpen,
        addItemForm:            store.addItemForm,
        addItemFormErrors:      store.addItemFormErrors,
        editItemFormOpen:       store.editItemFormOpen,
        editItemFormTarget:     store.editItemFormTarget,
        editItemForm:           store.editItemForm,
        editItemFormErrors:     store.editItemFormErrors,
        pullHistoryOpen:        store.pullHistoryOpen,
        pullHistoryTarget:      store.pullHistoryTarget,
        pullHistoryItems:       store.pullHistoryItems,
        pullHistoryLoading:     store.pullHistoryLoading,
        inventoryTabs: INVENTORY_TABS,
        enterInventoryView, switchInventoryTab,
        openPullForm, closePullForm, submitPull,
        openAddItemForm, closeAddItemForm, submitAddItem,
        openEditItemForm, closeEditItemForm, submitEditItem,
        confirmDeleteInventoryItem,
        openPullHistory, closePullHistory,

        // Completed Orders
        completedOrders:        store.completedOrders,
        completedOrdersLoading: store.completedOrdersLoading,
        enterCompletedOrdersView, loadCompletedOrders, restoreCompletedOrder,

        // Open Orders
        openOrders:               store.openOrders,
        openOrdersLoading:        store.openOrdersLoading,
        openOrdersSort:           store.openOrdersSort,
        openOrderSections:        store.openOrderSections,
        openOrderColorPickerRow:  store.openOrderColorPickerRow,
        openOrderEditingCell:     store.openOrderEditingCell,
        openOrderEditingValue:    store.openOrderEditingValue,
        openOrderSelectedIds:     store.openOrderSelectedIds,
        openOrderBulkStatus:      store.openOrderBulkStatus,
        openOrderDragOverSection: store.openOrderDragOverSection,
        openOrderDropZoneTarget:  store.openOrderDropZoneTarget,
        openOrderExpandedCols:    store.openOrderExpandedCols,
        openOrderAddModalOpen:    store.openOrderAddModalOpen,
        openOrderAddMode:         store.openOrderAddMode,
        openOrderAddForm:         store.openOrderAddForm,
        openOrderAddFormErrors:   store.openOrderAddFormErrors,
        openOrderAddPasteText:    store.openOrderAddPasteText,
        openOrderAddPasteRows:    store.openOrderAddPasteRows,
        openOrderStatuses:        OPEN_ORDER_STATUSES,
        chutePartStatuses:        CHUTE_PART_STATUSES,
        openOrderSortFields:      OPEN_ORDER_SORT_FIELDS,
        enterOpenOrdersView,
        loadOpenOrders,
        setSectionSort,
        openOrderSortIcon,
        setRowColor,
        effectiveRowColor,
        openOrderRowClass,
        reminderEmailModalOpen: store.reminderEmailModalOpen,
        reminderEmail:          store.reminderEmail,
        reminderEmailSaving:    store.reminderEmailSaving,
        saveReminderEmail,
        headerLinks:          store.headerLinks,
        headerLinksModalOpen: store.headerLinksModalOpen,
        headerLinksSaving:    store.headerLinksSaving,
        saveHeaderLinks,
        splashLinks:          store.splashLinks,
        splashLinksModalOpen: store.splashLinksModalOpen,
        splashLinksSaving:    store.splashLinksSaving,
        saveSplashLinks,
        openOrderColorDotClass,
        openOrderStatusClass,
        chuteStatusClass,
        openOrderHasLine3,
        cancelAddModal,
        parsePasteRows,
        saveOpenOrderRow,
        moveToSection, bulkChangeStatus,
        onRowMouseDown, onRowMouseEnter, onRowDragStart, onRowDragEnd,
        onSectionDragOver, onSectionDragLeave, onSectionDrop, clearRowSelection,
        onScrollAreaDragOver, onGripDragStart, onGripDragEnd,
        onDropZoneDragOver, clearDropZone, reorderDrop,
        startCellEdit, saveCellEdit, cancelCellEdit, deleteOpenOrder,
        toggleOpenOrderExpand,
        openOrderWoPanel:        store.openOrderWoPanel,
        openOrderWoPanelOrders:  store.openOrderWoPanelOrders,
        openOrderWoPanelLoading: store.openOrderWoPanelLoading,
        openWoDetailPanel, closeWoDetailPanel,
        woDeptBadgeClass, woStatusBadgeClass,
    };
}
